name: Run Emacs Tests

on:
  # Trigger this workflow on push or pull requests
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Emacs
    - name: Install Emacs
      run: |
        sudo apt-get update
        sudo apt-get install -y emacs-nox

    # Install Emacs dependencies (packages) in batch mode
    - name: Install Emacs Packages
      run: |
        emacs --batch \
          --eval "(require 'package)" \
          --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\") t)" \
          --eval "(package-initialize)" \
          --eval "(unless package-archive-contents (package-refresh-contents))" \
          --eval "(dolist (pkg '(request cl-lib transient auth-source json org)) (unless (package-installed-p pkg) (package-install pkg)))"

    # Set up and run the tests
    - name: Run Emacs tests
      run: |
        emacs --batch \
          --eval "(require 'ert)" \
          --load elm.el \
          --load elm.test.el \
          --eval '(ert-run-tests-batch-and-exit)'
